### ISSUE TITLE
Cannot modify header information - headers already sent by

### ISSUE THREAD

**Issue by webprogrammierer** [paysafecard/paysafecard-rest_api-php#11] opened 2018-01-03 19:41 UTC
> Warning: Cannot modify header information - headers already sent by (output started at /home/www/paysafecard/payment/index.php:1) in /home/www/paysafecard/payment/index.php on line 176

Original unchanged sample code shows this error.

**Comment by danadePSC** [comment] 2018-01-23 16:51
Hello @webprogrammierer Do you want to integrate paysafecard on your webshop or are you already a merchant? We tested the code and found no issue. We can support you during the integration process if you need.

**Comment by webprogrammierer** [comment] 2018-01-23 17:03
I have already integrated it.

But this error is a great problem:
In PHP it is not possible to use the header() command after(!) some output has be done. As you can see here
https://github.com/paysafecard/paysafecard-rest_api-php/blob/master/payment/index.php
you are outputting a lot of html and then after that you start the header() command.

This is impossible!!!
headers already sent by (output started at /home/www/paysafecard/payment/index.php:1) in /home/www/paysafecard/payment/index.php on line 176

Change this because it is not correct PHP code.

**Comment by danadePSC** [comment] 2018-01-23 17:14
Ok, thank you for your input. We will review the code and come back to you as soon as possible.

**Comment by dsentker** [comment] 2020-05-08 11:56
I have also tested the example and cannot confirm the error message. It works for me.

**Comment by danadePSC** [comment] 2020-05-08 12:11
We could also not reproduce the behavior described by the OP. We are closing this for now.

**Closed by danadePSC** 2020-05-08 12:11 UTC

**Comment by DemOnJR** [comment] 2020-05-15 20:43
the same error
